[gsheets]
type = "service_account"
project_id = "audit-procurement"
private_key_id = " "
private_key = """-----BEGIN PRIVATE KEY-----


-----END PRIVATE KEY-----"""
client_email = "streamlit-gsheet-access@audit-procurement.iam.gserviceaccount.com"
client_id = "104213023278817461958"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-gsheet-access@audit-procurement.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
