[gcp_service_account]
type = "service_account"
project_id = "milkstorage"
private_key_id = "c19c136137e4a1809eda8b0306b7abd077692b30"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDc0+zdynWeFVdj
h/jReD5/WUpbPvyHjMhsOlDjXWwcX2vAx9i11i5jRf/ke+rNIP2tuwc6qIZfath9
4A4EIXZljuBK1bcgzcAEVEmDLPlHRYZtR3mbexiLY0DNJc9J0wUVXNC1iDBqonpJ
I1myb9heR56/MrXllW3v47N5N/8BcpqqgRlRC0lc8IWCQhdqClOQfJeb8PtmUwOQ
906XEaUd9HbJGshNHDMcn+bzZyp1R5CykbYKRoXIvGU4xF7UlBd6qpRWycSg32a7
7rqtPFfsMwHAMq9GBQuVdmK2A/7B+qG1tBWw7I4zIatvV4FVdUJfIOKWANRGb7w3
Xzsm3GTRAgMBAAECggEAKu3mE93qjJ9gfEBwPiSOnco5etCdXiqfwe56UCEWxdNF
CtavCfaH0RPIId53MIaT2mTMDHq7mKwYRyw5/VKWBjtG3jV64t0s0YqjOeWR1mmt
LuxgtzmwdVSHwfnyOMtVpygCiO/fXbOVa0d8hgRZP0bUFR5iHy40D5koCE46/Egz
OtflygaKhlVabMzW7vJ4fNxhkJw2YYAl/cCQ0toc7AurP5ufsaE397Gi8Fs23Tme
Ls/aRuqTdKRRcR43XSzNnJvBrPyUMkM/U/+2MA9ab9PxJqwdarKeAr1SsdwK9OY/
7LjaGVysCktOkzu6639ysC6U/iWZNQI67PAxXQAAKwKBgQD56bkZlxnkpQXlF3T2
40fX2SlPO2DE7cHYUYP0zosweCtmsTPClJcldlgCiOFKA/dtg7cGTL1iuPBlpNJv
8er8fBdslFvyiPB3iLwJ7M6w3A1rwKdesP0fI0cGu5cMyAsMqe1BWH4dnqyuRKlS
LkdbwCmHgt/sqXsCg3SVLfV7kwKBgQDiNNklX3SpoZrw6IU31sssyuiy4ei236K1
7Kok1r4ZTL/srFXAQ0lalsRB+JxBoCavxJbuA7RuRuhWokS6dsFxXiGzxoXeafc9
vXrh3VJiysbbIyeHdgQfLLm2t2OiuBNaHNSWRcoRUVkcqY3XPWUskECfcq5OETUl
a47Qv0wEiwKBgQC0zelCoFT1XIa1RZEzhR9XBB+k2Pqbvr99dwwWss90k5wiwZUG
82Wejs4Bl3IWkGQT8TUa864YnGAfyW0N3GH7pPN1dKhJAdWnRV91dsPapHl5OXpd
QYL/YhBiyJjxgFCuKsoheppTZ5baxYYSlLS/pnjlN0Q1/i+mk+BmhUeSzQKBgQCl
iplzMUU2Ms8qCHAdqjJsKF5dMthUpJr12im15fWenD1EXeYvWs6e3gDoaqEnoaVO
Mmdl7g4oOfokFIKJlwkAByxQ3TLwzsmiRD1ed9Kn+8/FZRezmZlwmxGZ9uGSnnWD
F+A3zQEQ5WB6ilcEMqkNENBKH+oRtaQYK3uLpsNh+wKBgQCLC9ORWvY+fV639w/G
diNq3tXP4HsaUUGi0LrwE9UUZT3wpsZI3YxWMQqmXngFVkFN8UOQJHcRZLDcg+Xx
gTzIsXQwDdnah4j2EsMZ881Tn0OJq5anVy5bSvRnBxdKOgk6ZpU4ZHfb15G/2/FM
wC3hnqhPS9/3/C5zImK1HJiTEg==
-----END PRIVATE KEY-----"""
client_email = "streamlit-gsheet-access@milkstorage.iam.gserviceaccount.com"
client_id = "104195162651675564694"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-gsheet-access@milkstorage.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[drive]
# ID двух папок в Google Drive, куда будут сохраняться отчёты в виде CSV
order_lists_id = "1Be7ADhQ-rxZdOs-GknzCKc_BjAoWvPh7"
inventariz_id  = "1aX2SKbOqYc5NdBIcfzP4-Ro0HanTWmPe"
